import { Roboto } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/lib/redux/provider/provider";

const roboto = Roboto({
  weight: ["400", "600", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.className} antialiased`}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
